<?xml version="1.0"?>
<robot name="base" xmlns:xacro="http://ros.org/wiki/xacro"> 

    <xacro:macro name="box_inertia" params="m l w h">
        <inertia  ixx="${m*(h*h+w*w)/12}" ixy = "0" ixz = "0"
                iyy="${m*(l*l+h*h)/12}" iyz = "0"
                izz="${m*(w*w+l*l)/12}" /> 
    </xacro:macro>
    <xacro:macro name="robot_base">
        <link name="base_footprint">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.001 0.001 0.001" />
                </geometry>
            </visual>
        </link>
        <joint name="base_footprint_link_joint" type="fixed">
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
            <parent link="base_footprint"/>
            <child link="base_link" />
        </joint>
        <link name="base_link">
            <inertial>
                <mass value="${base_mass}" />
                <origin xyz="0.0 0 0.0" />
                <!--The 3x3 rotational inertia matrix. -->
                <xacro:box_inertia  m="${base_mass}" l="${base_length}" w="${base_width}" h="${base_height}" />
            </inertial>    
            <visual>
                <origin xyz="0.0 0 ${base_height/2}" rpy="0 0 0" /> 
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}" />
                </geometry>
            </visual>  
            <collision>
                <origin xyz="0 0 0" />
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}" />
                </geometry>
            </collision>
        </link>
    </xacro:macro>
</robot>

