<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">

	<!-- ***************** -->
	<!-- Imported elements -->
	<!-- ***************** -->
	<xacro:arg name="use_nominal_extrinsics" default="false" />

    <xacro:include filename="parameter.xacro" />
	<!-- import xacro files for the aitoXS robot -->
	<!-- import the robot base xacro file  -->
	<xacro:include filename="base.xacro" />

	<!-- import the robot wheel xacro file  -->
	<xacro:include filename="wheel.xacro" />
	<xacro:include filename="caster.xacro" />
	<xacro:include filename="sensors.xacro" />

	<xacro:robot_base />
	<xacro:robot_wheel prefix="left" parent="base_link" angle="-1"/>
	<xacro:robot_wheel prefix="right" parent="base_link" angle="1"/>
	<xacro:robot_caster prefix="front" parent="base_link" front="1"/>
	<xacro:robot_caster prefix="back" parent="base_link" front="-1"/>

	<xacro:sensor_imu prefix="base" parent="base_link" rate="30"/>
	<xacro:sensor_2dlidar prefix="base" parent="base_link" rate="30"/>
	<gazebo>
	<plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>
		<ros>
			<!-- Set namespace -->
			<namespace>/differential_drive_controller</namespace>
		</ros>

		<!-- Replace camelCase elements with camel_case ones -->
		<update_rate>50</update_rate>
		<left_joint>left_wheel_joint</left_joint>
		<right_joint>right_wheel_joint</right_joint>
		<wheel_separation>${track}</wheel_separation>
		<wheel_diameter>${2*wheel_radius}</wheel_diameter>
		<odometry_frame>odom</odometry_frame>

		<!-- wheelTorque and wheelAcceleration now have max_ prefix -->
		<max_wheel_torque>20</max_wheel_torque>
		<max_acceleration>1.0</max_acceleration>
		<!-- output -->
		<publish_odom>true</publish_odom>
		<publish_odom_tf>true</publish_odom_tf>

		<odometry_frame>odom</odometry_frame>
		<robot_base_frame>base_footprint</robot_base_frame>
	</plugin>
	</gazebo>
	<gazebo>
		<plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
			<update_rate>2</update_rate>
			<joint_name>left_wheel_joint</joint_name>
			<joint_name>right_wheel_joint</joint_name>
		</plugin>
	</gazebo>
</robot>

